# Generated by Django 5.2.9 on 2026-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_payment_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('stripe', 'Stripe')], default='cash', max_length=20),
        ),
    ]
