# Generated by Django 5.2.9 on 2026-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa')], default='cash', max_length=20),
        ),
    ]
