# Generated by Django 5.2.9 on 2026-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, default='medicines/default.png', null=True, upload_to='medicines/'),
        ),
    ]
