# Generated by Django 5.2.9 on 2026-03-12 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0001_initial'),
        ('pharmacy', '0006_alter_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='RemarkMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('time_of_day', models.CharField(blank=True, max_length=100, null=True)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_medicines', to='pharmacy.medicine')),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='appointment.remark')),
            ],
        ),
    ]
