# Generated by Django 5.2.9 on 2026-03-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remark_remarkmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarkmedicine',
            name='time_of_day',
        ),
    ]
