# Generated by Django 5.2.9 on 2026-04-03 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_remarkmedicine_time_of_day'),
        ('doctor', '0003_remove_payment_price_payment_doctor_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'time_slot'), name='unique_doctor_date_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'appointment_date', 'time_slot'), name='unique_patient_date_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('time_slot', 'date'), name='unique_timeslot_date_booking'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time_slot'), name='unique_user_date_timeslot_booking'),
        ),
    ]
