# Generated by Django 5.2.9 on 2026-04-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_unique_doctor_date_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_appointments', to='appointment.appointment'),
        ),
    ]
