# Generated by Django 5.2.9 on 2026-04-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_follow_up_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='follow_up_of',
        ),
    ]
