# Generated by Django 5.2.9 on 2026-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkmedicine',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
