# Generated by Django 5.2.9 on 2026-04-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remarkmedicine_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarkmedicine',
            name='payment_method',
        ),
    ]
