# Generated by Django 5.2.9 on 2026-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='departments', to='accounts.disease'),
        ),
    ]
